export const symbolData = {
  "simbolo-01": "Controle de Estabilidade do Veículo",
  "simbolo-02": "ASR – Advertência do Painel de Instrumentos piscando",
  "simbolo-03": "LDWS – Sistema de aviso de saída da faixa",
  "simbolo-04": "ASR – Desativado",
  "simbolo-05": "AEBS – Desativado",
  "simbolo-06": "Catalisador SCR",
  "simbolo-07": "Advertência geral",
  "simbolo-08": "Bloqueio do diferencial entre eixos (longitudinal)",
  "simbolo-09": "Bloqueio do diferencial entre rodas (eixo cruzado)",
  "simbolo-10": "Tomada de Força (PTO)",
  "simbolo-11": "Indicador de direção à esquerda",
  "simbolo-12": "Indicador de direção à direita",
  "simbolo-13": "Falha de lâmpada",
  "simbolo-14": "Farol principal – luz alta",
  "simbolo-15": "Faróis de neblina dianteiros",
  "simbolo-16": "Advertência do airbag",
  "simbolo-17": "Lembrete do cinto de segurança",
  "simbolo-18": "Auxílio de partida em aclives",
  "simbolo-19": "ABS do caminhão",
  "simbolo-20": "ABS do reboque / carreta",
  "simbolo-21": "Advertência geral da carroçaria",
  "simbolo-22": "Freio motor ativo",
  "simbolo-23": "Freio de estacionamento",
  "simbolo-24": "Freios com baixo desempenho",
  "simbolo-25": "Faróis de neblina traseiros",
  "simbolo-26": "Indicador de avaria",
  "simbolo-27": "Alta temperatura do sistema de escapamento",
  "simbolo-28": "Chassi fora da altura de direção normal",
  "simbolo-29": "Pré-aquecedor da admissão do motor",
  "simbolo-30": "Advertência do tacógrafo",
  "simbolo-31": "Travamento da cabine está aberto",
  "simbolo-32": "ARLA32 incorreto / mau funcionamento",
  "simbolo-33": "Advertência EAS – limite de velocidade 20 km/h",
  "simbolo-34": "Nível do líquido de arrefecimento muito baixo",
  "simbolo-35": "Temperatura do líquido de arrefecimento muito alta",
  "simbolo-36": "Advertência do alternador",
  "simbolo-37": "Nível de óleo do motor baixo",
  "simbolo-38": "Advertência do motor",
  "simbolo-39": "Advertência da transmissão",
  "simbolo-40": "Controlador central do veículo – Falha VICE",
  "simbolo-41": "Nível do óleo: alto / baixo (corrigir nível)",
  "simbolo-42": "Sobrecarga ou desgaste da embreagem",
  "simbolo-43": "Desgaste na lona do freio",
  "simbolo-44": "Advertência vermelha – adicionar óleo",
  "simbolo-45": "Advertência do sistema ACC",
  "simbolo-46": "Nível de combustível baixo",
  "simbolo-47": "Nível de ARLA32 baixo",
  "simbolo-48": "Filtro de partículas cheio",
  "simbolo-49": "Drenar pré-filtro de combustível",
  "simbolo-50": "Luz de trabalho",
  "simbolo-51": "Aviso geral de perigo"
};
