// app/simbolos-painel/symbolData.ts

export type SymbolInfo = {
  id: number;        // número 1..51
  slug: string;      // "simbolo-01", "simbolo-20" etc. (sem extensão)
  title: string;     // nome técnico que aparece na tela
  description: string;
};

export const symbolData: SymbolInfo[] = [
  { id: 1, slug: "simbolo-01", title: "Controle de Estabilidade do Veículo", description: "" },
  { id: 2, slug: "simbolo-02", title: "ASR – Advertência do Painel de Instrumentos piscando", description: "" },
  { id: 3, slug: "simbolo-03", title: "LDWS – Sistema de aviso de saída da faixa", description: "" },
  { id: 4, slug: "simbolo-04", title: "ASR – Desativado", description: "" },
  { id: 5, slug: "simbolo-05", title: "AEBS – Desativado", description: "" },
  { id: 6, slug: "simbolo-06", title: "Catalisador SCR", description: "" },
  { id: 7, slug: "simbolo-07", title: "Advertência geral", description: "" },
  { id: 8, slug: "simbolo-08", title: "Bloqueio do diferencial entre eixos (longitudinal)", description: "" },
  { id: 9, slug: "simbolo-09", title: "Bloqueio do diferencial entre rodas (eixo cruzado)", description: "" },
  { id: 10, slug: "simbolo-10", title: "Tomada de Força (PTO)", description: "" },
  { id: 11, slug: "simbolo-11", title: "Indicador de direção à esquerda", description: "" },
  { id: 12, slug: "simbolo-12", title: "Indicador de direção à direita", description: "" },
  { id: 13, slug: "simbolo-13", title: "Falha de lâmpada", description: "" },
  { id: 14, slug: "simbolo-14", title: "Farol principal – luz alta", description: "" },
  { id: 15, slug: "simbolo-15", title: "Faróis de neblina dianteiros", description: "" },
  { id: 16, slug: "simbolo-16", title: "Advertência do airbag", description: "" },
  { id: 17, slug: "simbolo-17", title: "Lembrete do cinto de segurança", description: "" },
  { id: 18, slug: "simbolo-18", title: "Auxílio de partida em aclives", description: "" },
  { id: 19, slug: "simbolo-19", title: "ABS do caminhão", description: "" },
  { id: 20, slug: "simbolo-20", title: "ABS do reboque / carreta", description: "" },
  { id: 21, slug: "simbolo-21", title: "Advertência geral da carroçaria", description: "" },
  { id: 22, slug: "simbolo-22", title: "Freio motor ativo", description: "" },
  { id: 23, slug: "simbolo-23", title: "Freio de estacionamento", description: "" },
  { id: 24, slug: "simbolo-24", title: "Freios com baixo desempenho", description: "" },
  { id: 25, slug: "simbolo-25", title: "Faróis de neblina traseiros", description: "" },
  { id: 26, slug: "simbolo-26", title: "Indicador de avaria", description: "" },
  { id: 27, slug: "simbolo-27", title: "Alta temperatura do sistema de escapamento", description: "" },
  { id: 28, slug: "simbolo-28", title: "Chassi fora da altura de direção normal", description: "" },
  { id: 29, slug: "simbolo-29", title: "Pré-aquecedor da admissão do motor", description: "" },
  { id: 30, slug: "simbolo-30", title: "Advertência do tacógrafo", description: "" },
  { id: 31, slug: "simbolo-31", title: "Travamento da cabine está aberto", description: "" },
  { id: 32, slug: "simbolo-32", title: "ARLA32 incorreto / mau funcionamento", description: "" },
  { id: 33, slug: "simbolo-33", title: "Advertência EAS – limite de velocidade 20 km/h", description: "" },
  { id: 34, slug: "simbolo-34", title: "Nível do líquido de arrefecimento muito baixo", description: "" },
  { id: 35, slug: "simbolo-35", title: "Temperatura do líquido de arrefecimento muito alta", description: "" },
  { id: 36, slug: "simbolo-36", title: "Advertência do alternador", description: "" },
  { id: 37, slug: "simbolo-37", title: "Nível de óleo do motor baixo", description: "" },
  { id: 38, slug: "simbolo-38", title: "Advertência do motor", description: "" },
  { id: 39, slug: "simbolo-39", title: "Advertência da transmissão", description: "" },
  { id: 40, slug: "simbolo-40", title: "Controlador central do veículo – Falha VICE", description: "" },
  { id: 41, slug: "simbolo-41", title: "Nível do óleo: alto / baixo (corrigir nível)", description: "" },
  { id: 42, slug: "simbolo-42", title: "Sobrecarga ou desgaste da embreagem", description: "" },
  { id: 43, slug: "simbolo-43", title: "Desgaste na lona do freio", description: "" },
  { id: 44, slug: "simbolo-44", title: "Advertência vermelha – adicionar óleo", description: "" },
  { id: 45, slug: "simbolo-45", title: "Advertência do sistema ACC", description: "" },
  { id: 46, slug: "simbolo-46", title: "Nível de combustível baixo", description: "" },
  { id: 47, slug: "simbolo-47", title: "Nível de ARLA32 baixo", description: "" },
  { id: 48, slug: "simbolo-48", title: "Filtro de partículas cheio", description: "" },
  { id: 49, slug: "simbolo-49", title: "Drenar pré-filtro de combustível", description: "" },
  { id: 50, slug: "simbolo-50", title: "Luz de trabalho", description: "" },
  { id: 51, slug: "simbolo-51", title: "Aviso geral de perigo", description: "" },
];
